//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidSafe.Entities.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidSafe.Entities.Validation.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided authentication method is not supported.
        /// </summary>
        public static string AuthMethodNotSupported {
            get {
                return ResourceManager.GetString("AuthMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No areas provided in collection..
        /// </summary>
        public static string EmptyAreas {
            get {
                return ResourceManager.GetString("EmptyAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchMessage does not contain any AreaMatches or BluetoothMatches..
        /// </summary>
        public static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seeds provided in collection..
        /// </summary>
        public static string EmptySeeds {
            get {
                return ResourceManager.GetString("EmptySeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Message identifier (must be a GUID/UUID)..
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Message identifier (cannot use zeroed value)..
        /// </summary>
        public static string InvalidGuidEmpty {
            get {
                return ResourceManager.GetString("InvalidGuidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Latitude (must be between {1} and {2})..
        /// </summary>
        public static string InvalidLatitude {
            get {
                return ResourceManager.GetString("InvalidLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Longitude (must be between {1} and {2})..
        /// </summary>
        public static string InvalidLongitude {
            get {
                return ResourceManager.GetString("InvalidLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision &apos;{0}&apos; is outside allowable range ({1} to {2})..
        /// </summary>
        public static string InvalidPrecision {
            get {
                return ResourceManager.GetString("InvalidPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid seed (must be a GUID/UUID)..
        /// </summary>
        public static string InvalidSeed {
            get {
                return ResourceManager.GetString("InvalidSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time &apos;{0}&apos; occurs after end time &apos;{1}&apos;..
        /// </summary>
        public static string InvalidStartEndTimeSequence {
            get {
                return ResourceManager.GetString("InvalidStartEndTimeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid timestamp (must be greater than zero, in UTC, and be reported in milliseconds since the UNIX epoch)..
        /// </summary>
        public static string InvalidTimestamp {
            get {
                return ResourceManager.GetString("InvalidTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid timestamp (violates age restriction)..
        /// </summary>
        public static string InvalidTimestampAge {
            get {
                return ResourceManager.GetString("InvalidTimestampAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication header is missing..
        /// </summary>
        public static string MissingAuthenticationHeader {
            get {
                return ResourceManager.GetString("MissingAuthenticationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location property is null or empty..
        /// </summary>
        public static string NullLocation {
            get {
                return ResourceManager.GetString("NullLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region property is null or empty..
        /// </summary>
        public static string NullRegion {
            get {
                return ResourceManager.GetString("NullRegion", resourceCulture);
            }
        }
    }
}
