// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace CovidSafe.API.v20200611.Protos
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Area : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"location")]
        public Location Location { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"radius_meters")]
        public float RadiusMeters { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"begin_time")]
        public long BeginTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"end_time")]
        public long EndTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Location : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"latitude")]
        public double Latitude { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"longitude")]
        public double Longitude { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MessageInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MessageId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"message_timestamp")]
        public long MessageTimestamp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MessageListRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"region")]
        public Region Region { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last_query_time")]
        public long LastQueryTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MessageListResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message_info")]
        public global::System.Collections.Generic.List<MessageInfo> MessageInfoes { get; } = new global::System.Collections.Generic.List<MessageInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"max_response_timestamp")]
        public long MaxResponseTimestamp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"requested_queries")]
        public global::System.Collections.Generic.List<MessageInfo> RequestedQueries { get; } = new global::System.Collections.Generic.List<MessageInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MessageResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"narrowcast_messages")]
        public global::System.Collections.Generic.List<NarrowcastMessage> NarrowcastMessages { get; } = new global::System.Collections.Generic.List<NarrowcastMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NarrowcastMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserMessage { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"area")]
        public Area Area { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Region : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"latitude_prefix")]
        public int LatitudePrefix { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"longitude_prefix")]
        public int LongitudePrefix { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"precision")]
        public int Precision { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestValidationResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"failures")]
        public global::System.Collections.Generic.List<RequestValidationFailure> Failures { get; } = new global::System.Collections.Generic.List<RequestValidationFailure>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestValidationFailure : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"property")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Property { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion